# Generated by Django 5.2.7 on 2025-10-03 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_media_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='genre',
        ),
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'Select Type'), ('movie', 'Movie'), ('book', 'Book'), ('game', 'Game')], null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('', 'Select Rating'), (1, '1 - Terrible'), (2, '2 - Very Bad'), (3, '3 - Bad'), (4, '4 - Poor'), (5, '5 - Average'), (6, '6 - Fine'), (7, '7 - Good'), (8, '8 - Very Good'), (9, '9 - Great'), (10, '10 - Masterpiece')], null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Select Status'), ('plan_to_watch', 'Plan to Watch'), ('watching', 'Currently Watching'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('dropped', 'Dropped')], null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
