# Generated by Django 5.2.7 on 2025-10-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_media_genre_media_type_alter_media_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Select Status'), ('consuming', 'Currently Consuming'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('dropped', 'Dropped'), ('plan_to_consume', 'Plan to Consume')], null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'Select Type'), ('movie', 'Movie'), ('book', 'Book'), ('game', 'Game'), ('series', 'Series'), ('anime', 'Anime'), ('manga', 'Manga'), ('tv_show', 'TV Show'), ('podcast', 'Podcast'), ('other', 'Other')], null=True),
        ),
    ]
