# Generated by Django 5.2.7 on 2025-10-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_media_status_alter_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Select Status'), ('consuming', 'Consuming'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('dropped', 'Dropped'), ('plan_to_consume', 'Plan to Consume')], null=True),
        ),
    ]
