# Generated by Django 5.2.7 on 2025-10-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_media_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Select Status'), ('consuming', 'Consuming'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('dropped', 'Dropped'), ('planned', 'Planned')], null=True),
        ),
    ]
