# Generated by Django 5.2.7 on 2025-10-04 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_media_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Select Status'), ('consuming', 'Consuming'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('dropped', 'Dropped'), ('planned', 'Planned')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(blank=True, choices=[('', 'Select Type'), ('movie', 'Movie'), ('book', 'Book'), ('game', 'Game'), ('series', 'Series'), ('anime', 'Anime'), ('manga', 'Manga'), ('tv_show', 'TV Show'), ('podcast', 'Podcast'), ('other', 'Other')], max_length=30, null=True),
        ),
    ]
